export const DELETE_INGREDIENT_IN_CONSTRUCTOR = 'DELETE_INGREDIENT_IN_CONSTRUCTOR';
export const INSERT_INGREDIENT_IN_CONSTRUCTOR = 'INSERT_INGREDIENT_IN_CONSTRUCTOR';
export const ADD_BUN_TO_BURGER_CONSTRUCTOR = 'ADD_BUN_TO_BURGER_CONSTRUCTOR';
export const ADD_TOPPING_TO_BURGER_CONSTRUCTOR = 'ADD_TOPPING_TO_BURGER_CONSTRUCTOR';
// export const SET_INGREDIENTS_FOR_BURGER_CONSTRUCTOR =
//   "SET_INGREDIENTS_FOR_BURGER_CONSTRUCTOR";