export const INCREASE_COUNTER_INGREDIENT = 'INCREASE_COUNTER_INGREDIENT';
export const DECREASE_COUNTER_INGREDIENT = 'DECREASE_COUNTER_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
